<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <LangVersion>$(CSharpLangVersion)</LangVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>icons\iva-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Model\**" />
    <EmbeddedResource Remove="Model\**" />
    <None Remove="Model\**" />
    <Page Remove="Model\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="icons\iva-icon.ico" />
    <None Remove="icons\iva-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icons\iva-icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="icons\iva-icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(MicrosoftExtensionsDependencyInjectionVersion)" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(MicrosoftExtensionsHostingVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IntensityMapping.Core\IntensityMapping.Core.csproj" />
    <ProjectReference Include="..\..\src\IntensityValueGeneration\IntensityValueGeneration.csproj" />
    <ProjectReference Include="..\..\src\WpfIntensityView\WpfIntensityView.csproj" />
  </ItemGroup>

</Project>
