<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net6.0-windows;net48</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IntensityValueGeneration\IntensityValueGeneration.csproj" />
    <ProjectReference Include="..\..\src\IntensityView\IntensityView.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Model\" />
  </ItemGroup>

</Project>
