<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <LangVersion>$(CSharpLangVersion)</LangVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FontConversions.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="$(SystemDrawingCommonVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IntensityMapping.Core\IntensityMapping.Core.csproj" />
  </ItemGroup>

</Project>
